### ISSUE TITLE
Cant use if you ever forgot to close client

### ISSUE THREAD

**Issue by Ianyourgod** [null8626/python-weather#23]
I got an error message before I was able to close the client and now when ever I try to make another client I get this error message(btw I am using discord.py):
`Ignoring exception in command weather:
Traceback (most recent call last):
  File "C:\Users\ianlo_btxmkkk\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 
85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ianlo_btxmkkk\visualstudio\botstf\bot.py", line 64, in weather
    weather = await client.find(city)
  File "C:\Users\ianlo_btxmkkk\AppData\Local\Programs\Python\Python310\lib\site-packages\python_weather\client.py", line 37, 
in find
    return await self.http.request(location)
  File "C:\Users\ianlo_btxmkkk\AppData\Local\Programs\Python\Python310\lib\site-packages\python_weather\rest.py", line 24, in request
    parsed = parse(self.cache[url])
  File "C:\Users\ianlo_btxmkkk\AppData\Local\Programs\Python\Python310\lib\site-packages\xmltodict.py", line 378, in parse   
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ianlo_btxmkkk\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\ianlo_btxmkkk\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 
863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\ianlo_btxmkkk\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 
94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ExpatError: not well-formed (invalid token): line 1, column 0
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E846501960>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001E8465448E0>, 850371.0)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001E846501990>`

Edit:

MY CODE:

@bot.command()
async def weather(ctx, city="Austin TX"):
    client = python_weather.Client(format=python_weather.IMPERIAL)
    weather = await client.find(city)
    await ctx.reply(f"The current tempature in {city} is {weather.current.temperature}.")
    await client.close()

**Comment by null8626** [comment]
Related to #25
