### ISSUE TITLE
ValueError: 308 is not a valid WeatherType

### ISSUE THREAD

**Issue by ethanlchristensen** [null8626/python-weather#44]
Attempted to get the weather for the following location,

Puerto Ingeniero Ibáñez, Coihaique, Chile

```Traceback (most recent call last):
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\modal.py", line 187, in _scheduled_task
    await self.on_submit(interaction)
  File "C:\Users\ethan\source\repos\DiscordBot\BOT\_utils\modals.py", line 43, in on_submit
    weather = await Weather(self.children[0].value, self._typE)
  File "C:\Users\ethan\source\repos\DiscordBot\BOT\_utils\weather.py", line 7, in get_weather
    print(response)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\python_weather\forecast.py", line 645, in __repr__
    return f'<Weather current={self.current!r} location={self.location!r}>'
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\python_weather\forecast.py", line 330, in __repr__
    return f'<CurrentForecast temperature={self.temperature!r} description={self.description!r} type=\'{self.type!r}\'>'
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\python_weather\forecast.py", line 316, in type
    return WeatherType._new(int(self.__inner['weatherCode'])) # inspired by Rust <3
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\python_weather\enums.py", line 54, in _new
    return WeatherType(num)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 308 is not a valid WeatherType```

**Comment by ethanlchristensen** [comment]
![image](https://github.com/null8626/python-weather/assets/55725575/eb80e4b3-64ff-457a-9242-d3ef56d89008)
An example test code I have made

**Comment by null8626** [comment]
thank you for this, will look into it!

**Comment by null8626** [comment]
i'm afraid you are using an older version of `python-weather`, have you considered updating your `python-weather` version to the current one?

try `pip install python-weather --upgrade` and rerun the example code again!

**Comment by ethanlchristensen** [comment]
Updating the version solved the issue!

**Comment by null8626** [comment]
No problem! Glad to help!
